name: Deploy Embalagens to IONOS

on:
  push:
    branches:
      - main
    paths:
      - 'embalagens/**'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to IONOS via SFTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy embalagens folder to IONOS
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22
          local_path: ./embalagens/*
          remote_path: /grafica/embalagens/
          sftp_only: true
